import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os'; import {join,resolve} from 'node:path'; import {fileURLToPath} from 'node:url';
const root=resolve(fileURLToPath(new URL('..',import.meta.url))),httpPort=8767;
const edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',base=`http://127.0.0.1:${httpPort}`;
const pages=['/','/de-bai.html',...Array.from({length:7},(_,i)=>`/solutions/q${i+1}.html`)],sizes=[375,768,1200],sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitPort(p){for(let i=0;i<80;i++){try{return +((await readFile(join(p,'DevToolsActivePort'),'utf8')).split(/\r?\n/)[0])}catch{}await sleep(100)}throw Error('DevToolsActivePort timeout')}
function cdp(url){const ws=new WebSocket(url),p=new Map();let id=0;const open=new Promise((o,e)=>{ws.onopen=o;ws.onerror=e});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&p.has(m.id)){p.get(m.id)(m);p.delete(m.id)}};return{ws,open,call:async(method,params={})=>{await open;return new Promise((o,e)=>{const n=++id;p.set(n,m=>m.error?e(Error(JSON.stringify(m.error))):o(m.result));ws.send(JSON.stringify({id:n,method,params}))})}}}
async function ev(c,e){return (await c.call('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true})).result.value}
const profile=await mkdtemp(join(tmpdir(),'na-layout-')),server=spawn('python',['-m','http.server',String(httpPort),'--bind','127.0.0.1','--directory',root],{stdio:'ignore',windowsHide:true});let browser;
try{for(let i=0;i<50;i++){try{const r=await fetch(base+'/index.html');if(r.ok)break}catch{}await sleep(100)}browser=spawn(edge,['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,base+'/'],{stdio:'ignore',windowsHide:true});const port=await waitPort(profile);let tabs;for(let i=0;i<50;i++){try{tabs=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();if(tabs.length)break}catch{}await sleep(100)}const tab=tabs.find(t=>t.type==='page'),c=cdp(tab.webSocketDebuggerUrl);await c.open;await c.call('Page.enable');
for(const width of sizes){await c.call('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});for(const path of pages){await c.call('Page.navigate',{url:base+path});for(let i=0;i<80;i++){if(await ev(c,"document.readyState==='complete'"))break;await sleep(100)}await sleep(180);const m=await ev(c,"({vw:innerWidth,sw:document.documentElement.scrollWidth,fonts:document.fonts.status})");assert.ok(m.sw<=m.vw+2,`${path} overflows ${m.sw-m.vw}px at ${width}px`);assert.equal(m.fonts,'loaded',`${path} fonts not loaded at ${width}px`)}}
const ver=await (await fetch(`http://127.0.0.1:${port}/json/version`)).json();const bc=cdp(ver.webSocketDebuggerUrl);await bc.open;await bc.call('Browser.close').catch(()=>{});bc.ws.close();c.ws.close();console.log('LAYOUT SANITY: PASS (375/768/1200, all 9 pages, no horizontal overflow)');
}finally{server.kill();if(browser&&!browser.killed)browser.kill();await sleep(200);await rm(profile,{recursive:true,force:true}).catch(()=>{})}
