import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
const root=resolve(fileURLToPath(new URL('..',import.meta.url))),edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',sleep=ms=>new Promise(r=>setTimeout(r,ms));
const server=createServer(async(req,res)=>{try{if(req.url==='/probe.html'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><meta charset="utf-8"><section id="q3GeometryTool"></section><script type="module" src="/tools/q3-interactive.js"></script>');return}const p=join(root,decodeURIComponent(req.url.split('?')[0]));res.setHeader('content-type',extname(p)==='.js'?'text/javascript; charset=utf-8':'text/plain; charset=utf-8');res.end(await readFile(p))}catch{res.statusCode=404;res.end('not found')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port,profile=await mkdtemp(join(tmpdir(),'q3-label-'));let browser,client;
async function waitPort(){const p=join(profile,'DevToolsActivePort');for(let i=0;i<100;i++){try{return Number((await readFile(p,'utf8')).split(/\r?\n/)[0])}catch{}await sleep(80)}throw Error('DevToolsActivePort timeout')}
function cdp(url){const ws=new WebSocket(url),pending=new Map();let seq=0;const opened=new Promise((ok,bad)=>{ws.onopen=ok;ws.onerror=bad});ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}};return{ws,opened,call:async(method,params={})=>{await opened;return new Promise((ok,bad)=>{const id=++seq;pending.set(id,m=>m.error?bad(Error(JSON.stringify(m.error))):ok(m.result));ws.send(JSON.stringify({id,method,params}))})}}}
async function ev(expr){const r=await client.call('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.text+': '+(r.exceptionDetails.exception?.description||''));return r.result.value}try{
 browser=spawn(edge,['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,`http://127.0.0.1:${port}/probe.html`],{stdio:'ignore',windowsHide:true});const dp=await waitPort();
 let tabs;for(let i=0;i<80;i++){try{tabs=await (await fetch(`http://127.0.0.1:${dp}/json/list`)).json();if(tabs.some(t=>t.type==='page'))break}catch{}await sleep(80)}client=cdp(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await client.opened;await client.call('Page.enable');await client.call('Page.navigate',{url:`http://127.0.0.1:${port}/probe.html`});
 for(let i=0;i<100;i++){if(await ev("!!document.querySelector('#q3GeometrySvg')"))break;await sleep(80)}assert.equal(await ev("!!document.querySelector('#q3GeometrySvg')"),true,'Q3 probe did not render');
 const bad=await ev(`(()=>{const ds=[60,100,150,220,300],bad=[],R=document.querySelector('[data-distance]'),side=document.querySelector('[data-side]');
 const audit=(tag)=>{const svg=document.querySelector('#q3GeometrySvg'),texts=[...svg.querySelectorAll('text')],lines=[...svg.querySelectorAll('line')],circle=svg.querySelector('.main-circle'),boxes=texts.map(t=>({n:t.textContent.trim(),b:t.getBBox(),t}));const inside=(b,x,y)=>x>=b.x-2&&x<=b.x+b.width+2&&y>=b.y-2&&y<=b.y+b.height+2;
 for(const {n,b,t} of boxes){const p=svg.querySelector('[data-point='+n+']'),dx=+t.getAttribute('x')-+p.getAttribute('cx'),dy=+t.getAttribute('y')-+p.getAttribute('cy');if(Math.min(Math.abs(dx),Math.abs(dy))>=.75)bad.push(tag+':'+n+':diagonal');for(const l of lines){const x1=+l.getAttribute('x1'),y1=+l.getAttribute('y1'),x2=+l.getAttribute('x2'),y2=+l.getAttribute('y2');for(let i=0;i<=60;i++){const u=i/60;if(inside(b,x1+(x2-x1)*u,y1+(y2-y1)*u)){bad.push(tag+':'+n+':line');break}}}const cx=+circle.getAttribute('cx'),cy=+circle.getAttribute('cy'),r=+circle.getAttribute('r');for(let i=0;i<300;i++){const a=2*Math.PI*i/300;if(inside(b,cx+r*Math.cos(a),cy+r*Math.sin(a))){bad.push(tag+':'+n+':circle');break}}}
 for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];if(!(a.b.x+a.b.width+2<b.b.x||b.b.x+b.b.width+2<a.b.x||a.b.y+a.b.height+2<b.b.y||b.b.y+b.b.height+2<a.b.y))bad.push(tag+':'+a.n+'-'+b.n+':labels')}};
 for(let s=0;s<2;s++){for(const d of ds){R.value=String(d);R.dispatchEvent(new Event('input',{bubbles:true}));audit((s?'left':'right')+'/'+d)}side.click()}return bad})()`);
 assert.deepEqual(bad,[],`Q3 label collisions: ${bad.join(', ')}`);console.log('Q3 LABEL SANITY: PASS (cardinal-only, geometry/label collision-free across 10 slider/side states)');
}finally{if(client)client.ws.close();if(browser&&!browser.killed)browser.kill();server.close();await sleep(200);await rm(profile,{recursive:true,force:true}).catch(()=>{})}