from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
S={
1:r'''<section class="statement"><span class="label">Đề bài</span><p>Cho đa thức hệ số thực \(P(x)\) có bậc \(d\ge5\), hệ số cao nhất bằng \(1\) và \(P'(x)>0\) với mọi \(x\ge1\). Xét dãy số \((x_n)_{n\ge1}\) xác định bởi \[x_1=1,\qquad x_{n+1}=\frac{P'(n)}{P(n+1)-P(n)}x_n,\qquad \forall n\ge1.\]</p><p>a) Xét dãy số \((y_n)_{n\ge1}\) xác định bởi \[y_n=n\left(\frac{P(n+1)-P(n)}{P'(n)}-1\right),\qquad n\ge1.\] Chứng minh rằng các dãy \((x_n),(y_n)\) đều hội tụ và tìm các giới hạn tương ứng.</p><p>b) Đặt \(z_n=x_1+x_2+\cdots+x_n\). Chứng minh rằng dãy \((z_n)\) hội tụ.</p></section>''',
2:r'''<section class="statement"><span class="label">Đề bài</span><p>Cho hàm số \(f:\mathbb R^+\to\mathbb R^+\) thỏa mãn \(f(1)=1\) và \[f(x)+f(y)+f(z)+f(t)\le f(x+y+z+t)\le4\max\{f(x),f(y),f(z),f(t)\}\] với mọi \(x,y,z,t>0\).</p><p>a) Chứng minh rằng \(f\) tăng ngặt và \(f(2026)=2026\).</p><p>b) Tìm tất cả hàm số \(f\) thỏa mãn bài toán.</p></section>''',
3:r'''<section class="statement"><span class="label">Đề bài</span><p>Cho tam giác \(ABC\) nhọn nội tiếp đường tròn \((O)\), trực tâm \(H\). Điểm \(P\) di động trên đường thẳng \(BC\) và nằm ngoài đoạn \(BC\). \(OP\) lần lượt cắt \(AC,AB\) tại \(Q,R\). Dựng \(Y,Z\) lần lượt là hình chiếu của \(Q,R\) lên \(AB,AC\).</p><p>a) Chứng minh rằng \(YZ\) luôn đi qua một điểm cố định khi \(P\) thay đổi.</p><p>b) Gọi giao điểm của \(QY\) và \(RZ\) là \(S\), \(SH\) và \(YZ\) là \(X\). Chứng minh rằng \(XA\perp XP\).</p></section>''',
4:r'''<section class="statement"><span class="label">Đề bài</span><p>Cho số nguyên dương \(k>1\). Với mỗi số nguyên dương \(n\), gọi \(\sigma_k(n)\) là tổng lũy thừa bậc \(k\) của các ước nguyên dương của \(n\). Gọi \(n\) là một số tốt nếu \(n\mid\sigma_k(n)\).</p><p>a) Chứng minh rằng \(\sigma_k(n)\) là hàm nhân tính và tồn tại một dãy vô hạn các số tốt \(n_1<n_2<n_3<\cdots\) sao cho \(n_i\mid n_{i+1}\) với mọi \(i\ge1\).</p><p>b) Chứng minh rằng với mọi số nguyên dương \(r\), tồn tại một số tốt có ít nhất \(r\) ước nguyên tố phân biệt.</p></section>''',
5:r'''<section class="statement"><span class="label">Đề bài</span><p>Cho tam giác \(ABC\) không cân ngoại tiếp đường tròn \((I)\). Đường tròn \((I)\) tiếp xúc với \(BC,CA,AB\) lần lượt tại \(D,E,F\). Gọi \(K\) là trực tâm của tam giác \(BIC\).</p><p>a) \(CK,BK\) lần lượt cắt \(DE,DF\) tại \(S,T\), và \(ST\) cắt \(EF\) tại \(R\). Chứng minh rằng \(IR\perp AK\).</p><p>b) Chứng minh rằng \(AK,BC\) và đường thẳng Euler của tam giác \(KBC\) đồng quy hoặc đôi một song song.</p></section>''',
6:r'''<section class="statement"><span class="label">Đề bài</span><p>Cho đa thức monic \[P(x)=x^n+a_{n-1}x^{n-1}+\cdots+a_1x+a_0,\] với \(n>2\), hệ số thực, tất cả nghiệm của \(P(x)\) đều là số thực và khác \(0\).</p><p>a) Chứng minh rằng \(2026a_k^2+2027a_{k+1}^2>0\) với mọi \(k=0,1,\ldots,n-2\).</p><p>b) Hỏi số lượng hệ số khác \(0\) của đa thức \(P(x)\) nhỏ nhất là bao nhiêu?</p></section>''',
7:r'''<section class="statement"><span class="label">Đề bài</span><p>Cho hai số nguyên \(n,k\) thỏa mãn \(2\le k<n\). Trong một lễ hội, có \(n\) ngọn đèn được đặt trên một vòng tròn và đánh số \(1,2,\ldots,n\) theo chiều kim đồng hồ. Mỗi ngọn đèn ở một trong hai trạng thái: sáng hoặc tắt.</p><p>Trong mỗi lượt ghi, trạng thái của các ngọn đèn được giữ cố định. Một người đi quanh vòng tròn theo chiều kim đồng hồ. Khi đứng tại ngọn đèn thứ \(i\), người đó ghi lại số ngọn đèn đang sáng trong \(k\) ngọn đèn liên tiếp theo chiều kim đồng hồ, bắt đầu từ ngọn đèn thứ \(i\); sau ngọn đèn thứ \(n\) lại đến ngọn đèn thứ \(1\). Gọi số ghi được tại ngọn đèn thứ \(i\) là \(s_i\). Sau một vòng, người đó thu được bản ghi \((s_1,s_2,\ldots,s_n)\).</p><p>a) Xác định điều kiện của \(n,k\) để với mọi cách bố trí trạng thái của các ngọn đèn, bản ghi \((s_1,s_2,\ldots,s_n)\) xác định duy nhất cách bố trí đó.</p><p>b) Trong suốt lễ hội, trạng thái của các ngọn đèn có thể được thay đổi tùy ý giữa các lượt ghi. Xác định số bản ghi \((s_1,s_2,\ldots,s_n)\) phân biệt có thể thu được.</p></section>'''
}

for i,section in S.items():
    path=ROOT/f'solutions/q{i}.html'
    text=path.read_text(encoding='utf-8-sig')
    new,count=re.subn(r'<section class="statement">.*?</section>',lambda _m: section,text,count=1,flags=re.S)
    if count!=1: raise SystemExit(f'expected one statement in q{i}, got {count}')
    path.write_text(new,encoding='utf-8')
    print(f'updated q{i}')
